/* El Canon de Occidente — dataset del grafo (v0.2)
   g: grupo | d: fechas | s: resumen | w: título en es.wikipedia.org | t: título en es.wikisource.org */
window.CANON = (function () {
  'use strict';

  var GROUPS = {
    persona: { label: 'Personas', color: '#6ea8fe' },
    obra:    { label: 'Obras',    color: '#b28cff' },
    idea:    { label: 'Ideas',    color: '#4ade80' },
    evento:  { label: 'Eventos',  color: '#fb923c' },
    lugar:   { label: 'Lugares',  color: '#22d3ee' }
  };

  var NODES = [
    /* ---------- PERSONAS ---------- */
    { id:'homero', n:'Homero', g:'persona', d:'s. VIII a. C.',
      s:'Poeta al que la tradición atribuye la Ilíada y la Odisea. Punto de partida de la literatura occidental.', w:'Homero' },
    { id:'socrates', n:'Sócrates', g:'persona', d:'470–399 a. C.',
      s:'No escribió una línea: enseñó preguntando. Su juicio y su muerte fundan la figura del filósofo.', w:'Sócrates' },
    { id:'platon', n:'Platón', g:'persona', d:'427–347 a. C.',
      s:'Discípulo de Sócrates y fundador de la Academia. Convierte el diálogo en sistema filosófico.', w:'Platón' },
    { id:'aristoteles', n:'Aristóteles', g:'persona', d:'384–322 a. C.',
      s:'Discípulo de Platón y maestro de Alejandro. Organiza el saber entero en disciplinas separadas.', w:'Aristóteles' },
    { id:'herodoto', n:'Heródoto', g:'persona', d:'484–425 a. C.',
      s:'«Padre de la historia»: narra las guerras médicas mezclando indagación, viaje y relato.', w:'Heródoto' },
    { id:'tucidides', n:'Tucídides', g:'persona', d:'460–400 a. C.',
      s:'Historiador de la guerra del Peloponeso. Inaugura el análisis frío del poder político.', w:'Tucídides' },
    { id:'pericles', n:'Pericles', g:'persona', d:'495–429 a. C.',
      s:'Estratego que lleva la democracia ateniense y su cultura a su punto más alto.', w:'Pericles' },
    { id:'alejandro', n:'Alejandro Magno', g:'persona', d:'356–323 a. C.',
      s:'Su conquista difunde la lengua y la cultura griegas desde Egipto hasta la India.', w:'Alejandro Magno' },
    { id:'zenon', n:'Zenón de Citio', g:'persona', d:'334–262 a. C.',
      s:'Fundador del estoicismo, que enseñaba en el Pórtico pintado de Atenas.', w:'Zenón de Citio' },
    { id:'ciceron', n:'Cicerón', g:'persona', d:'106–43 a. C.',
      s:'Orador y filósofo que traslada al latín el vocabulario conceptual griego.', w:'Cicerón' },
    { id:'cesar', n:'Julio César', g:'persona', d:'100–44 a. C.',
      s:'General y político cuyo poder personal quiebra definitivamente la República romana.', w:'Julio César' },
    { id:'augusto', n:'Augusto', g:'persona', d:'63 a. C. – 14 d. C.',
      s:'Primer emperador: transforma la República en Imperio conservando todas sus formas.', w:'Augusto' },
    { id:'virgilio', n:'Virgilio', g:'persona', d:'70–19 a. C.',
      s:'Poeta de la Eneida, el mito fundacional de Roma escrito bajo el patrocinio de Augusto.', w:'Virgilio' },
    { id:'seneca', n:'Séneca', g:'persona', d:'4 a. C. – 65 d. C.',
      s:'Estoico romano y tutor de Nerón. Entiende la filosofía como ejercicio práctico diario.', w:'Séneca' },
    { id:'marcoaurelio', n:'Marco Aurelio', g:'persona', d:'121–180',
      s:'Emperador estoico que escribe para sí mismo un cuaderno de disciplina interior.', w:'Marco Aurelio' },

    /* ---------- OBRAS ---------- */
    { id:'iliada', n:'Ilíada', g:'obra', d:'s. VIII a. C.',
      s:'La cólera de Aquiles ante Troya: honor, mortalidad y furia.', w:'Ilíada', t:'Ilíada' },
    { id:'odisea', n:'Odisea', g:'obra', d:'s. VIII a. C.',
      s:'El regreso de Ulises: astucia, hospitalidad y el deseo de volver a casa.', w:'Odisea', t:'Odisea' },
    { id:'apologia', n:'Apología de Sócrates', g:'obra', d:'c. 399–390 a. C.',
      s:'La defensa de Sócrates ante el tribunal ateniense, escrita por Platón.', w:'Apología de Sócrates', t:'Apología de Sócrates' },
    { id:'republica', n:'República', g:'obra', d:'c. 375 a. C.',
      s:'Qué es la justicia y cómo sería la ciudad ideal. Contiene el mito de la caverna.', w:'República (Platón)', t:'República' },
    { id:'etica', n:'Ética a Nicómaco', g:'obra', d:'c. 340 a. C.',
      s:'La felicidad como actividad conforme a la virtud, buscada en el término medio.', w:'Ética a Nicómaco' },
    { id:'politica', n:'Política', g:'obra', d:'c. 335 a. C.',
      s:'Comparación de constituciones y definición del ser humano como animal político.', w:'Política (Aristóteles)' },
    { id:'metafisica', n:'Metafísica', g:'obra', d:'c. 335 a. C.',
      s:'La ciencia del ser en cuanto ser: causas, sustancia y motor inmóvil.', w:'Metafísica (Aristóteles)' },
    { id:'historias', n:'Historias', g:'obra', d:'c. 430 a. C.',
      s:'La indagación de Heródoto sobre el choque entre griegos y persas.', w:'Historias (Heródoto)' },
    { id:'peloponesolibro', n:'Historia de la guerra del Peloponeso', g:'obra', d:'c. 400 a. C.',
      s:'Crónica de Tucídides sobre la guerra que arruinó la hegemonía de Atenas.', w:'Historia de la guerra del Peloponeso' },
    { id:'degallico', n:'La guerra de las Galias', g:'obra', d:'c. 51 a. C.',
      s:'César narra su propia conquista en tercera persona: parte militar y propaganda.', w:'Comentarios sobre la guerra de las Galias' },
    { id:'eneida', n:'Eneida', g:'obra', d:'29–19 a. C.',
      s:'Eneas huye de Troya y funda el linaje de Roma: Homero reescrito en latín.', w:'Eneida', t:'Eneida' },
    { id:'cartaslucilio', n:'Cartas a Lucilio', g:'obra', d:'c. 65',
      s:'Cartas de Séneca sobre el tiempo, la muerte y el dominio de uno mismo.', w:'Cartas a Lucilio' },
    { id:'meditaciones', n:'Meditaciones', g:'obra', d:'c. 170–180',
      s:'Notas privadas de Marco Aurelio escritas en campaña militar, sin intención de publicarlas.', w:'Meditaciones', t:'Meditaciones' },

    /* ---------- IDEAS ---------- */
    { id:'mayeutica', n:'Mayéutica', g:'idea', d:'s. V a. C.',
      s:'Preguntar hasta que el otro dé a luz su propio saber. El método de Sócrates.', w:'Mayéutica' },
    { id:'ideas', n:'Mundo de las ideas', g:'idea', d:'s. IV a. C.',
      s:'Lo que vemos es copia imperfecta de formas eternas e inteligibles.', w:'Mundo de las ideas' },
    { id:'logica', n:'Lógica aristotélica', g:'idea', d:'s. IV a. C.',
      s:'El silogismo: reglas para que una conclusión se siga necesariamente de sus premisas.', w:'Lógica aristotélica' },
    { id:'arete', n:'Areté', g:'idea', d:'s. VIII–IV a. C.',
      s:'Excelencia: cumplir de forma óptima la función que a cada cosa le es propia.', w:'Areté' },
    { id:'retorica', n:'Retórica', g:'idea', d:'s. IV a. C.',
      s:'El arte de encontrar, en cada caso, los medios de persuasión disponibles.', w:'Retórica (Aristóteles)' },
    { id:'democracia', n:'Democracia ateniense', g:'idea', d:'508–322 a. C.',
      s:'Asamblea, sorteo y rotación de cargos: el poder en manos de los ciudadanos.', w:'Democracia ateniense' },
    { id:'estoicismo', n:'Estoicismo', g:'idea', d:'s. III a. C. – s. II',
      s:'Distinguir lo que depende de nosotros de lo que no, y vivir conforme a la naturaleza.', w:'Estoicismo' },
    { id:'derechoromano', n:'Derecho romano', g:'idea', d:'s. V a. C. – s. VI',
      s:'El armazón jurídico sobre el que se levantan casi todos los códigos europeos.', w:'Derecho romano' },

    /* ---------- EVENTOS ---------- */
    { id:'guerrasmedicas', n:'Guerras médicas', g:'evento', d:'499–449 a. C.',
      s:'Las polis griegas frenan al Imperio persa y nace la conciencia de un «nosotros» griego.', w:'Guerras médicas' },
    { id:'siglopericles', n:'Siglo de Pericles', g:'evento', d:'461–429 a. C.',
      s:'Apogeo ateniense: Partenón, tragedia y democracia radical en una sola generación.', w:'Siglo de Pericles' },
    { id:'guerrapeloponeso', n:'Guerra del Peloponeso', g:'evento', d:'431–404 a. C.',
      s:'Atenas contra Esparta: la guerra civil griega que acaba con la hegemonía ateniense.', w:'Guerra del Peloponeso' },
    { id:'juicio', n:'Juicio de Sócrates', g:'evento', d:'399 a. C.',
      s:'Condenado por impiedad y por corromper a los jóvenes; se niega a huir y bebe la cicuta.', w:'Juicio de Sócrates' },
    { id:'helenismo', n:'Helenismo', g:'evento', d:'323–31 a. C.',
      s:'Tras Alejandro, la cultura griega se vuelve cosmopolita y se mezcla con Oriente.', w:'Helenismo' },
    { id:'idusmarzo', n:'Asesinato de César', g:'evento', d:'44 a. C.',
      s:'Los idus de marzo: el Senado mata al dictador y desata la última guerra civil.', w:'Julio César' },
    { id:'accio', n:'Batalla de Accio', g:'evento', d:'31 a. C.',
      s:'Octavio derrota a Antonio y Cleopatra: fin de la República, principio del Imperio.', w:'Batalla de Accio' },
    { id:'caida', n:'Caída de Roma', g:'evento', d:'476',
      s:'Depuesto el último emperador de Occidente; el legado romano pasa a otras manos.', w:'Caída del Imperio romano de Occidente' },

    /* ---------- LUGARES ---------- */
    { id:'atenas', n:'Atenas', g:'lugar', d:'—',
      s:'Ciudad de la democracia, la tragedia y la filosofía.', w:'Atenas' },
    { id:'esparta', n:'Esparta', g:'lugar', d:'—',
      s:'Polis militar y oligárquica: el contramodelo permanente de Atenas.', w:'Esparta' },
    { id:'academia', n:'Academia', g:'lugar', d:'387–86 a. C.',
      s:'Escuela fundada por Platón en las afueras de Atenas; funcionó tres siglos.', w:'Academia platónica' },
    { id:'liceo', n:'Liceo', g:'lugar', d:'335 a. C.',
      s:'Escuela de Aristóteles. Se enseñaba paseando, de ahí «peripatéticos».', w:'Liceo (Antigua Grecia)' },
    { id:'alejandria', n:'Alejandría', g:'lugar', d:'331 a. C.',
      s:'Capital cultural del helenismo, fundada por Alejandro en el delta del Nilo.', w:'Alejandría' },
    { id:'biblioteca', n:'Biblioteca de Alejandría', g:'lugar', d:'s. III a. C.',
      s:'El intento de reunir en un solo lugar todo el saber escrito del mundo conocido.', w:'Biblioteca de Alejandría' },
    { id:'roma', n:'Roma', g:'lugar', d:'753 a. C. – 476',
      s:'De aldea del Lacio a imperio mediterráneo. Heredera y transmisora de Grecia.', w:'Antigua Roma' }
  ];

  var EDGES = [
    ['homero','iliada','escribió'],
    ['homero','odisea','escribió'],
    ['iliada','arete','encarna'],
    ['odisea','arete','encarna'],
    ['iliada','eneida','modelo de'],
    ['homero','virgilio','influye en'],

    ['socrates','platon','maestro de'],
    ['socrates','mayeutica','practicó'],
    ['socrates','juicio','protagoniza'],
    ['socrates','atenas','vivió en'],
    ['socrates','apologia','retratado en'],
    ['socrates','arete','indagó'],
    ['mayeutica','apologia','aparece en'],

    ['platon','apologia','escribió'],
    ['platon','republica','escribió'],
    ['platon','ideas','formuló'],
    ['platon','academia','fundó'],
    ['platon','aristoteles','maestro de'],
    ['platon','atenas','vivió en'],
    ['platon','democracia','criticó'],
    ['republica','ideas','expone'],
    ['republica','democracia','critica'],
    ['republica','arete','discute'],
    ['academia','ideas','enseña'],

    ['aristoteles','etica','escribió'],
    ['aristoteles','politica','escribió'],
    ['aristoteles','metafisica','escribió'],
    ['aristoteles','logica','fundó'],
    ['aristoteles','retorica','sistematizó'],
    ['aristoteles','liceo','fundó'],
    ['aristoteles','alejandro','maestro de'],
    ['aristoteles','ideas','refutó'],
    ['aristoteles','atenas','enseñó en'],
    ['etica','arete','analiza'],
    ['politica','democracia','analiza'],
    ['logica','metafisica','sirve a'],
    ['liceo','logica','enseña'],

    ['herodoto','historias','escribió'],
    ['historias','guerrasmedicas','narra'],
    ['herodoto','guerrasmedicas','indagó'],
    ['tucidides','peloponesolibro','escribió'],
    ['peloponesolibro','guerrapeloponeso','narra'],
    ['tucidides','guerrapeloponeso','testigo de'],
    ['tucidides','atenas','vivió en'],
    ['tucidides','pericles','retrató a'],

    ['pericles','atenas','gobernó'],
    ['pericles','democracia','impulsó'],
    ['pericles','siglopericles','da nombre a'],
    ['pericles','guerrapeloponeso','inicia'],
    ['siglopericles','atenas','sucede en'],
    ['siglopericles','democracia','apogeo de'],

    ['guerrasmedicas','atenas','implica a'],
    ['guerrasmedicas','esparta','implica a'],
    ['guerrapeloponeso','atenas','enfrenta a'],
    ['guerrapeloponeso','esparta','enfrenta a'],
    ['guerrapeloponeso','juicio','contexto de'],
    ['esparta','arete','cultiva'],

    ['alejandro','helenismo','origina'],
    ['alejandro','alejandria','fundó'],
    ['helenismo','alejandria','centro en'],
    ['alejandria','biblioteca','alberga'],
    ['biblioteca','historias','conserva'],
    ['helenismo','estoicismo','contexto de'],
    ['helenismo','roma','absorbido por'],

    ['zenon','estoicismo','fundó'],
    ['zenon','atenas','enseñó en'],
    ['estoicismo','seneca','practicado por'],
    ['estoicismo','marcoaurelio','practicado por'],
    ['seneca','cartaslucilio','escribió'],
    ['cartaslucilio','estoicismo','expone'],
    ['marcoaurelio','meditaciones','escribió'],
    ['meditaciones','estoicismo','expone'],
    ['marcoaurelio','roma','gobernó'],
    ['seneca','roma','vivió en'],

    ['ciceron','retorica','maestro de'],
    ['ciceron','roma','vivió en'],
    ['ciceron','estoicismo','divulgó'],
    ['ciceron','derechoromano','ejerció'],
    ['ciceron','cesar','se opuso a'],
    ['retorica','democracia','instrumento de'],

    ['cesar','degallico','escribió'],
    ['cesar','idusmarzo','protagoniza'],
    ['cesar','roma','gobernó'],
    ['idusmarzo','augusto','desencadena'],
    ['augusto','accio','vence en'],
    ['augusto','roma','gobernó'],
    ['augusto','virgilio','protege a'],
    ['virgilio','eneida','escribió'],
    ['eneida','roma','mitifica'],
    ['accio','roma','transforma'],

    ['roma','derechoromano','produce'],
    ['roma','caida','termina en'],
    ['derechoromano','caida','sobrevive a'],
    ['roma','atenas','heredera de']
  ];

  return { GROUPS: GROUPS, NODES: NODES, EDGES: EDGES };
})();
